# Site settings
title: Ralph Marschall
description: "Ralph Marschall's website."
#url: 'http://ra1phm.github.io' 
#url: 'http://localhost:4000'
url: 'http://ralphmarschall.lu'

#include:     ['.htaccess']
exclude:     ['/sass', '/.sass-cache','/venv', '/temp', 'jekyll-post.py', 'requirements.txt', 'README.md']

#paginate: 5

markdown: kramdown
markdown_ext: markdown,md
permalink: pretty

highlighter: pygments
#pygments: true