# Site settings
title: Ralph Marschall
email: your-email@domain.com
description: "Ralph Marschall's website."
baseurl: ""
url: "localhost:4000"
#url: "http://www.ralphmarschall.lu"

#include:     ['.htaccess']
exclude:     ['/sass', '/.sass-cache','/venv', '/temp', 'jekyll-post.py', 'requirements.txt', 'README.md']

#paginate: 5

markdown: kramdown
markdown_ext: markdown,md
permalink: pretty

highlighter: pygments
#pygments: true